// User-requested custom widgets, generated by Claude, approval-gated.
//
// Security model (the part that matters):
// - Generated HTML NEVER runs in the app's origin. The frontend renders it in
//   an <iframe sandbox="allow-scripts"> with srcdoc — no same-origin, so no
//   cookies, storage, or parent DOM — plus a CSP of default-src 'none', so no
//   network of any kind. The only input is a JSON snapshot of the user's own
//   parsed data injected into the frame.
// - Widgets are per-user, capped, and only render after the user explicitly
//   approves a preview.

const crypto = require('crypto');
const Anthropic = require('@anthropic-ai/sdk');
const { getUser, updateUser } = require('./db');

const MODEL = 'claude-opus-5';
const MAX_WIDGETS = 8;

let client = null;
const getClient = () => (client = client || new Anthropic());

const WIDGET_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['title', 'description', 'span', 'html'],
  properties: {
    title: { type: 'string', description: 'Widget card title, max ~4 words.' },
    description: { type: 'string', description: 'One line under the title saying what it shows, max ~12 words.' },
    span: { type: 'string', enum: ['4', '6', '12'], description: 'Card width: 4 = third, 6 = half, 12 = full row. Pick the smallest that fits the content.' },
    html: { type: 'string', description: 'The complete widget body: one fragment containing <style>, markup, and one <script>. Self-contained.' },
  },
};

const SYSTEM_PROMPT = `You build ONE small dashboard widget for a personal habit/journal dashboard, from the user's description.

EXECUTION ENVIRONMENT — hard constraints:
- Your html runs inside a sandboxed iframe with CSP default-src 'none'. There is NO network access: no fetch/XHR/WebSockets, no external scripts, stylesheets, fonts, or images (http/https URLs will simply fail). data: URIs for images are allowed. No cookies, no localStorage.
- Everything must be self-contained vanilla HTML/CSS/JS in the single fragment you return: one <style> block, markup, one <script> block. No libraries.
- Read the user's data like this, at the top of your script:
    const DATA = JSON.parse(document.getElementById('cw-data').textContent);
  The element is guaranteed to exist before your script runs.
- Never ask the user to input data; no forms. Interactivity (hover, click-to-toggle views) is fine.
- Keep the whole fragment under 12KB.

DATA — exact shape of the parsed snapshot (fields can be null/empty; handle that gracefully with a short friendly message rather than breaking):
{
  habits: {
    habitNames: string[],
    days: [{ date: "YYYY-MM-DD", values: {habitName: bool}, done: int, total: int, completion: 0..1, note: string|null }]  // oldest→newest, up to 60
  },
  journal: [{ date, score: 0-10|null, city: string|null, bedtimeMin: int|null /* minutes vs midnight, -30=11:30pm, 75=1:15am */,
              activities: [{ time: "H:MM", title, location: string|null, rating: 0-10|null, people: string[] }] }],
  insights: {
    kpis: { completion7, completionPrev7, avgScore7, avgScoreAll, beforeMidnightRate, avgBedtimeMin },   // numbers or null
    perHabit: [{ name, rate: 0..1, done, total, currentStreak, bestStreak, avgScoreWith, avgScoreWithout }],
    people: [{ name, acts, days, avgDayScore, avgActRating }],
    cities: [{ city, days, avgScore }],
    sleep: [{ date, bedtimeMin, score }],
    plant: { daily: [{ date, count, solo, social, score, avgRating }], total },   // 🌱 sessions
    weekdays: [{ weekday: "MON".."SUN", completion, avgScore, n }],
    activities: [{ title, n, avgRating }]
  }
}

STYLE — match the host app:
- Font is inherited (system-ui). Text color #202124, secondary #5f6368, muted #80868b.
- Greens #188038 / #0d652d are the primary accent; yellow #f9ab00, blue #1a73e8, red #c5221f as accents; light green tint #e6f4ea; grid lines #e8eaed; card background is white (host provides it — use transparent body background, no outer border/shadow/margin).
- Rounded corners (10-14px) on inner elements, small uppercase labels (10-11px, letter-spacing .05em) like the host's section headers.
- Charts: inline SVG, thin marks, no chart libraries. Big numbers: bold, 28-34px.
- The frame auto-sizes to your content height (aim for 120-420px). Don't set html/body height.

QUALITY:
- Compute honestly from DATA. Never invent numbers. If the data can't support the request, render the widget shell with a one-line "not enough data yet" note.
- Prefer the simplest faithful version of what was asked. No filler text, no lorem ipsum, no titles inside the fragment (the host renders the card title).`;

function newId() {
  return 'w' + crypto.randomBytes(5).toString('hex');
}

async function listCustomWidgets(email) {
  const user = await getUser(email);
  return (user && user.customWidgets) || [];
}

async function generateWidget(email, prompt) {
  const clean = String(prompt || '').trim().slice(0, 500);
  if (clean.length < 5) throw new Error('Describe the widget in a sentence or two.');
  const list = await listCustomWidgets(email);
  if (list.length >= MAX_WIDGETS) throw new Error(`${MAX_WIDGETS} custom widgets is the cap — delete one first.`);
  if (!process.env.ANTHROPIC_API_KEY) throw new Error('ANTHROPIC_API_KEY not set.');

  let result = null;
  for (let attempt = 0; attempt < 2 && !result; attempt++) {
    const response = await getClient().messages.create({
      model: MODEL,
      max_tokens: 20000,
      system: SYSTEM_PROMPT,
      output_config: { format: { type: 'json_schema', schema: WIDGET_SCHEMA } },
      messages: [{ role: 'user', content: `Build this widget: ${clean}` }],
    });
    if (response.stop_reason === 'refusal') throw new Error('The model declined this request.');
    const text = response.content.find((b) => b.type === 'text');
    if (!text) continue;
    const parsed = JSON.parse(text.text);
    if (parsed.html && parsed.title) result = parsed;
  }
  if (!result) throw new Error('Widget generation came back empty — try rewording.');
  if (result.html.length > 40000) throw new Error('Generated widget was too large — try something simpler.');

  const widget = {
    id: newId(),
    title: String(result.title).slice(0, 40),
    description: String(result.description || '').slice(0, 120),
    span: ['4', '6', '12'].includes(String(result.span)) ? Number(result.span) : 6,
    html: result.html,
    prompt: clean,
    status: 'pending',
    createdAt: new Date().toISOString(),
  };
  await updateUser(email, { customWidgets: [...list, widget] });
  return widget;
}

async function approveWidget(email, id) {
  const list = await listCustomWidgets(email);
  const w = list.find((x) => x.id === id);
  if (!w) throw new Error('No such widget.');
  w.status = 'approved';
  await updateUser(email, { customWidgets: list });
  return w;
}

async function deleteWidget(email, id) {
  const list = await listCustomWidgets(email);
  await updateUser(email, { customWidgets: list.filter((x) => x.id !== id) });
}

module.exports = { listCustomWidgets, generateWidget, approveWidget, deleteWidget };
